-- PlacementPro schema for Supabase/PostgreSQL.
-- Safe to run against the tables created by the earlier SQL script.

CREATE TABLE IF NOT EXISTS public.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    hashed_password TEXT NOT NULL,
    role VARCHAR(20) NOT NULL
        CONSTRAINT users_role_check CHECK (role IN ('student', 'recruiter', 'admin'))
);

CREATE TABLE IF NOT EXISTS public.student_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE REFERENCES public.users(id),
    branch VARCHAR(50) NOT NULL,
    cgpa DOUBLE PRECISION NOT NULL,
    graduation_year INTEGER NOT NULL,
    backlogs INTEGER NOT NULL DEFAULT 0,
    skills TEXT NOT NULL DEFAULT '',
    resume_url TEXT
);

CREATE TABLE IF NOT EXISTS public.jobs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recruiter_id INTEGER NOT NULL REFERENCES public.users(id),
    title VARCHAR(150) NOT NULL,
    company VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    job_type VARCHAR(20) NOT NULL,
    location VARCHAR(100) NOT NULL,
    package_lpa DOUBLE PRECISION NOT NULL,
    min_cgpa DOUBLE PRECISION NOT NULL DEFAULT 0,
    allowed_branches VARCHAR(200) NOT NULL DEFAULT 'ALL',
    max_backlogs INTEGER NOT NULL DEFAULT 0,
    deadline DATE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_approved BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS public.applications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INTEGER NOT NULL REFERENCES public.jobs(id),
    student_id INTEGER NOT NULL REFERENCES public.users(id),
    status VARCHAR(30) NOT NULL DEFAULT 'applied',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_job_student UNIQUE (job_id, student_id)
);

CREATE INDEX IF NOT EXISTS ix_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS ix_jobs_title ON public.jobs(title);
CREATE INDEX IF NOT EXISTS ix_jobs_company ON public.jobs(company);
DROP INDEX IF EXISTS public.idx_users_email;
DROP INDEX IF EXISTS public.idx_jobs_title;
DROP INDEX IF EXISTS public.idx_jobs_company;

-- Replace the earlier SQL script's status list, which did not include this app's
-- interview_scheduled status.
ALTER TABLE public.applications
    DROP CONSTRAINT IF EXISTS applications_status_check;
ALTER TABLE public.applications
    ADD CONSTRAINT applications_status_check
    CHECK (status IN ('applied', 'shortlisted', 'interview_scheduled', 'selected', 'rejected'));

-- Remove only the unusable placeholder admin row from the earlier SQL example.
DELETE FROM public.users
WHERE email = 'admin@placementpro.com'
  AND hashed_password = '$2b$12$your_bcrypt_hash_here';
